[package]
name = "eg-seven-segment"
version = "0.1.0"
authors = ["Ralf Fuest <mail@rfuest.de>"]
edition = "2018"
repository = "https://github.com/embedded-graphics/eg-seven-segment"
documentation = "https://docs.rs/embedded-graphics"
categories = ["embedded", "no-std"]
keywords = ["embedded-graphics", "font"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
# TODO: use embedded-graphics-core after
#       https://github.com/embedded-graphics/embedded-graphics/issues/505 is resolved
embedded-graphics = { git = "https://github.com/embedded-graphics/embedded-graphics.git"}
bitflags = "1.2.1"

[dev-dependencies]
embedded-graphics-simulator = { git = "https://github.com/embedded-graphics/simulator.git"}

# TODO: remove
[patch.crates-io]
embedded-graphics = { git = "https://github.com/embedded-graphics/embedded-graphics.git"}
embedded-graphics-simulator = { git = "https://github.com/embedded-graphics/simulator.git"}
